import * as THREE from './vendor/three.module.js';
import {places,categories,byId,inCategory,knowledge} from './data.js';
import {buildWorld,project,unproject,bounds,heightAt,lake,river,canal,roads} from './scene.js';
const $=s=>document.querySelector(s),world=$('#world');
const small=matchMedia('(max-width:900px)'),reduced=matchMedia('(prefers-reduced-motion:reduce)');
let selected='westlake',category='all',mode='free',renderer,scene,camera,landscape,flight=null,orbitPhase=0,orbitRadius=28,orbitHeight=15;
let speed=3.5,joy={x:0,y:0},rise=0,keys=new Set(),last=performance.now(),lastUi=0,toastTimer;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function sourceHTML(s){return s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`:`<span>${esc(s.title)}${s.note?`<br>${esc(s.note)}`:''}</span>`;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close());}
function sources(s){return s.map(sourceHTML).join('');}
function setGuide(expanded){$('#guide').classList.toggle('minimized',!expanded);$('#guide-teaser').setAttribute('aria-expanded',String(expanded));}
function renderGuide(){const p=byId[selected];$('#guide-teaser').innerHTML=`<span class="eyebrow">${esc(p.kind)} · ${esc(p.area)}</span><strong>${esc(p.name)}</strong><span class="chevron" aria-hidden="true">${$('#guide').classList.contains('minimized')?'＋':'−'}</span><small>${esc(p.tagline)}</small>`;
 $('#guide-content').innerHTML=`<p class="place-intro">${esc(p.intro)}</p><div class="fact-row">${p.facts.map(([a,b])=>`<div><small>${esc(a)}</small><strong>${esc(b)}</strong></div>`).join('')}</div><div class="guide-actions"><button id="guide-fly">飛近景點</button><button id="guide-orbit">環繞觀看</button></div>${p.sections.map(([t,b])=>`<h3>${esc(t)}</h3><p>${esc(b)}</p>`).join('')}<p class="position-note">${esc(p.position)}</p><div class="source-list"><b>資料來源</b>${sources(p.sources)}</div>`;
 $('#guide-content').scrollTop=0;$('#guide-fly').onclick=()=>{goTo(selected);if(small.matches)setGuide(false);};$('#guide-orbit').onclick=()=>{startOrbit();if(small.matches)setGuide(false);};
}
function renderCategories(){const el=$('#categories');el.innerHTML=categories.map(c=>`<button data-category="${c.id}" class="${category===c.id?'active':''}" style="--theme:${c.color}" aria-pressed="${category===c.id}"><b>${esc(c.name)}</b><span>${esc(c.subtitle)}</span></button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>setCategory(b.dataset.category));}
function renderStops(){const c=categories.find(c=>c.id===category),visible=inCategory(category);$('#category-title').textContent=`${c.name} · ${visible.length} 個地方`;$('#stops').innerHTML=visible.map(p=>`<li><button data-id="${p.id}" class="${selected===p.id?'active':''}" ${selected===p.id?'aria-current="true"':''}><span class="stop-number">${esc(p.icon)}</span><span class="stop-text"><strong>${esc(p.short)}</strong><small>${esc(p.kind)}</small></span></button></li>`).join('');$('#stops').querySelectorAll('button').forEach(b=>b.onclick=()=>{choose(b.dataset.id,true);if(small.matches)toggleExplorer(false);});}
function setCategory(id){if(!categories.some(c=>c.id===id))return;category=id;const visible=inCategory(id);if(!visible.some(p=>p.id===selected))choose(visible[0].id,false);renderCategories();renderStops();renderGuide();mapDirty=true;updateLabels();toast(`已顯示${categories.find(c=>c.id===id).name}景點`);}
function choose(id,fly=true){if(!byId[id])return;if(!inCategory(category).some(p=>p.id===id)){category='all';renderCategories();}selected=id;landscape?.select(id);renderGuide();renderStops();setGuide(!small.matches);updateLabels();mapDirty=true;if(fly)goTo(id);}
$('#guide-teaser').onclick=()=>{setGuide($('#guide').classList.contains('minimized'));$('#guide-teaser .chevron').textContent=$('#guide').classList.contains('minimized')?'＋':'−';};
function toggleExplorer(open){$('#explorer').classList.toggle('open',open);$('#show-explorer').setAttribute('aria-expanded',String(open));if(open&&small.matches)setGuide(false);}
$('#show-explorer').onclick=()=>toggleExplorer(!$('#explorer').classList.contains('open'));$('#close-explorer').onclick=()=>toggleExplorer(false);
$('#knowledge-cards').innerHTML=knowledge.map(k=>`<article class="knowledge-card"><span>${esc(k.label)}</span><h3>${esc(k.title)}</h3><p>${esc(k.text)}</p>${sources(k.sources)}</article>`).join('');
function showDialog(sel){resetInput();stopMotion();closeDialogs();$(sel).showModal();}
$('#city-knowledge').onclick=()=>showDialog('#info-dialog');$('#help').onclick=$('#model-note').onclick=()=>showDialog('#help-dialog');
document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#speed-select').onchange=e=>{speed=Number(e.target.value);toast(speed>10?'跨城速度：放開搖桿或按鍵即停':speed<1?'慢遊：適合近距離看建築與水鄉':'巡航：適合城市與山水之間移動');};
renderCategories();renderStops();setGuide(!small.matches);renderGuide();
const labels=places.map(p=>{const b=document.createElement('button');b.className='place-label';b.innerHTML=`<small>${esc(p.icon)}</small>${esc(p.short)}`;b.setAttribute('aria-label',`選擇${p.name}`);b.style.display='none';b.onclick=()=>choose(p.id,true);$('#labels').appendChild(b);return {p,b};});
// The north-up inset is drawn from the same editorial geometry as the 3D scene.
const map=$('#minimap'),ctx=map.getContext('2d'),mapState={scale:1,ox:0,oz:0},mapPins=[];let mapDirty=true;
function mapXY(x,z){return [mapState.ox+x*mapState.scale,mapState.oz+z*mapState.scale];}
function drawMap(){if(!ctx)return;const w=map.width,h=map.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#e4ebd9';ctx.fillRect(0,0,w,h);const box={minX:-145,maxX:365,minZ:-565,maxZ:190};const scale=Math.min((w-75)/(box.maxX-box.minX),(h-28)/(box.maxZ-box.minZ));mapState.scale=scale;mapState.ox=(w-(box.maxX+box.minX)*scale)/2;mapState.oz=(h-(box.maxZ+box.minZ)*scale)/2;
 function path(pts,c,width,fill=false){ctx.beginPath();pts.forEach(([x,z],i)=>{const[a,b]=mapXY(x,z);i?ctx.lineTo(a,b):ctx.moveTo(a,b);});ctx.strokeStyle=c;ctx.lineWidth=width;ctx.lineJoin='round';if(fill){ctx.closePath();ctx.fillStyle=c;ctx.fill();}else ctx.stroke();}
 path(lake,'#8bb4a5',1,true);path(river,'#8bb4a5',4);path(canal,'#a8c5b0',1.2);for(const r of roads)path(r.points,'#c9cfb1',.8);
 const c=categories.find(c=>c.id===category),visible=inCategory(category).map(p=>p.id);
 mapPins.length=0;for(const p of places){const [x,y]=mapXY(...project(p.lon,p.lat));const active=p.id===selected;ctx.beginPath();ctx.arc(x,y,active?5:3.4,0,Math.PI*2);ctx.fillStyle=active?'#194f44':visible.includes(p.id)?c.color:'#a4b29d';ctx.fill();ctx.strokeStyle='#fff8e7';ctx.lineWidth=1.5;ctx.stroke();mapPins.push({id:p.id,x,y});}
 ctx.font='24px sans-serif';ctx.fillStyle='#54735e';const hz=mapXY(15,0);ctx.fillText('杭州',hz[0]-67,hz[1]+12);const wz=mapXY(...project(120.486,30.749));ctx.fillText('烏鎮',wz[0]+12,wz[1]+7);ctx.font='19px sans-serif';ctx.fillStyle='#829177';ctx.fillText('嘉興・桐鄉',wz[0]+12,wz[1]+32);
 if(camera){const [x,y]=mapXY(camera.position.x,camera.position.z);if(x>=0&&x<=w&&y>=0&&y<=h){ctx.save();ctx.translate(x,y);ctx.rotate(-camera.rotation.y);ctx.beginPath();ctx.moveTo(0,-7);ctx.lineTo(-4,5);ctx.lineTo(4,5);ctx.closePath();ctx.fillStyle='#c27240';ctx.fill();ctx.restore();}}mapDirty=false;}
map.onclick=e=>{const r=map.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*map.width,y=(e.clientY-r.top)/r.height*map.height;const nearest=mapPins.map(p=>({...p,d:Math.hypot(p.x-x,p.y-y)})).sort((a,b)=>a.d-b.d)[0];if(nearest&&nearest.d<24){choose(nearest.id,true);if(small.matches)toggleExplorer(false);}else if(camera){goToPoint((x-mapState.ox)/mapState.scale,(y-mapState.oz)/mapState.scale);if(small.matches)toggleExplorer(false);}};
drawMap();
function setMode(m){mode=m;$('#free-mode').classList.toggle('active',m==='free');$('#orbit-mode').classList.toggle('active',m==='orbit');$('#free-mode').setAttribute('aria-pressed',String(m==='free'));$('#orbit-mode').setAttribute('aria-pressed',String(m==='orbit'));$('#mode-label').textContent=m==='orbit'?'環繞觀看':'自由探索';}
function stopMotion(){flight=null;setMode('free');}
function goToPoint(x,z,r=12){if(!camera)return;resetInput();setMode('free');const target=new THREE.Vector3(THREE.MathUtils.clamp(x,bounds.minX+15,bounds.maxX-15),heightAt(x,z)+.6,THREE.MathUtils.clamp(z,bounds.minZ+15,bounds.maxZ-15));const end=target.clone().add(new THREE.Vector3(r*.75,r*.8,r));beginFlight(end,target);}
function beginFlight(end,target){if(!camera)return;const distance=camera.position.distanceTo(end);const endCamera=camera.clone();endCamera.position.copy(end);endCamera.lookAt(target);if(reduced.matches){camera.position.copy(end);camera.quaternion.copy(endCamera.quaternion);flight=null;return;}
 flight={from:camera.position.clone(),to:end.clone(),qFrom:camera.quaternion.clone(),qTo:endCamera.quaternion.clone(),target,start:performance.now(),duration:Math.min(2300,1200+distance*2),arc:Math.min(distance*.18,70)};$('#mode-label').textContent='飛往目的地';}
function goTo(id){if(!camera)return;const p=byId[id],[x,z]=project(p.lon,p.lat);stopMotion();goToPoint(x,z,p.radius);}
function startOrbit(){if(!camera)return;resetInput();flight=null;const p=byId[selected],g=landscape.groups.get(selected);orbitRadius=p.radius*1.05;orbitHeight=p.radius*.68+g.position.y;orbitPhase=.65;setMode('orbit');if(reduced.matches){goTo(selected);toast('已按減少動態設定顯示固定視角');return;}}
$('#free-mode').onclick=()=>stopMotion();$('#orbit-mode').onclick=startOrbit;
$('#next-stop').onclick=()=>{const list=inCategory(category),i=list.findIndex(p=>p.id===selected);choose(list[(i+1)%list.length].id,true);};
$('#overview').onclick=()=>{if(!camera)return;stopMotion();resetInput();const target=new THREE.Vector3(115,0,-195),end=target.clone().add(new THREE.Vector3(0,490,320));beginFlight(end,target);if(small.matches){setGuide(false);toggleExplorer(false);}toast('杭州—烏鎮全域 · 可選景點返回低空');};
try{
 renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'default'});renderer.setPixelRatio(Math.min(devicePixelRatio,small.matches?1.4:1.7));renderer.setSize(world.clientWidth,world.clientHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;world.appendChild(renderer.domElement);
 scene=new THREE.Scene();scene.background=new THREE.Color('#b7d0c4');scene.fog=new THREE.Fog('#b7d0c4',130,500);camera=new THREE.PerspectiveCamera(48,world.clientWidth/world.clientHeight,.035,2200);camera.rotation.order='YXZ';camera.position.set(40,29,84);const start=project(byId.westlake.lon,byId.westlake.lat);camera.lookAt(start[0],.4,start[1]);
 scene.add(new THREE.HemisphereLight('#e9f3e0','#42634d',2.3));const sun=new THREE.DirectionalLight('#fff0ce',2.7);sun.position.set(-100,220,80);scene.add(sun);landscape=buildWorld(scene);$('#loading').remove();
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();resetInput();stopMotion();toast('3D畫面暫停，請重新整理；仍可閱讀景點介紹。');});
}catch(err){document.body.classList.add('no3d');$('#loading').className='error';$('#loading').innerHTML='<strong>這個瀏覽器未能啟動 3D</strong><p>你仍可由「景點」閱讀景點介紹。可改用支援 WebGL 的 Chrome、Safari 或 Edge 再試。</p><button id="dismiss-error">繼續閱讀</button>';$('#dismiss-error').onclick=()=>$('#loading').remove();toggleExplorer(true);console.error('3D initialization failed:',err);}
function updateLabels(){if(!camera||!landscape)return;camera.updateMatrixWorld();const occupied=[];const w=world.clientWidth,h=world.clientHeight;const list=[...labels].sort((a,b)=>(a.p.id===selected?-1:b.p.id===selected?1:0));for(const {p,b} of list){const g=landscape.groups.get(p.id);const v=g.position.clone();v.y+=1.8;const distance=camera.position.distanceTo(v);const dir=v.clone().sub(camera.position).normalize();const front=camera.getWorldDirection(new THREE.Vector3()).dot(dir)>.05;v.project(camera);const x=(v.x*.5+.5)*w,y=(-v.y*.5+.5)*h;const maxDistance=camera.position.y>140?1600:190;let visible=front&&v.z<1&&x>8&&x<w-8&&y>135&&y<h-163&&distance<maxDistance;
 const width=p.short.length*13+35,box={l:x-width/2,r:x+width/2,t:y-32,b:y+2};if(visible&&occupied.some(o=>!(o.r<box.l||o.l>box.r||o.b<box.t||o.t>box.b)))visible=false;if(visible){occupied.push(box);b.style.display='block';b.style.transform=`translate(${x}px,${y}px) translate(-50%,-100%)`;}else b.style.display='none';b.classList.toggle('active',p.id===selected);}}
function resetInput(){keys.clear();joy.x=joy.y=0;rise=0;$('#knob').style.transform='translate(0px,0px)';}
function constrain(){if(!camera)return;camera.position.x=THREE.MathUtils.clamp(camera.position.x,bounds.minX,bounds.maxX);camera.position.z=THREE.MathUtils.clamp(camera.position.z,bounds.minZ,bounds.maxZ);camera.position.y=THREE.MathUtils.clamp(camera.position.y,Math.max(.6,heightAt(camera.position.x,camera.position.z)+.6),700);camera.rotation.x=THREE.MathUtils.clamp(camera.rotation.x,-1.53,.35);}
const pointers=new Map();let dragged=false,pinchDistance=0,startPointer=null;
world.addEventListener('pointerdown',e=>{if(!camera)return;stopMotion();world.focus({preventScroll:true});world.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});startPointer={x:e.clientX,y:e.clientY};dragged=false;if(pointers.size===2){const[a,b]=[...pointers.values()];pinchDistance=Math.hypot(a.x-b.x,a.y-b.y);dragged=true;}});
world.addEventListener('pointermove',e=>{if(!camera||!pointers.has(e.pointerId))return;const old=pointers.get(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2){const[a,b]=[...pointers.values()],d=Math.hypot(a.x-b.x,a.y-b.y);moveForward((d-pinchDistance)*Math.max(camera.position.y*.006,.035));pinchDistance=d;dragged=true;return;}const dx=e.clientX-old.x,dy=e.clientY-old.y;if(startPointer&&Math.hypot(e.clientX-startPointer.x,e.clientY-startPointer.y)>6)dragged=true;camera.rotation.y-=dx*.004;camera.rotation.x-=dy*.0035;constrain();});
function endPointer(e){if(!pointers.has(e.pointerId))return;const wasMultiple=pointers.size>1;pointers.delete(e.pointerId);if(!dragged&&!wasMultiple&&e.type==='pointerup'&&landscape&&camera){const r=world.getBoundingClientRect(),mouse=new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height)*2+1),ray=new THREE.Raycaster();ray.setFromCamera(mouse,camera);const hits=ray.intersectObjects(landscape.roots,true);if(hits.length){let o=hits[0].object;while(o&&!o.userData.placeId)o=o.parent;if(o)choose(o.userData.placeId,true);}}dragged=true;startPointer=null;}
world.addEventListener('pointerup',endPointer);world.addEventListener('pointercancel',endPointer);world.addEventListener('lostpointercapture',e=>pointers.delete(e.pointerId));
function moveForward(amount){if(!camera)return;camera.position.addScaledVector(camera.getWorldDirection(new THREE.Vector3()),amount);constrain();}
world.addEventListener('wheel',e=>{if(!camera)return;e.preventDefault();stopMotion();moveForward(-Math.sign(e.deltaY)*Math.max(.25,camera.position.y*.08));},{passive:false});
let joyId=null;const stick=$('#joystick');function updateJoy(e){const r=stick.getBoundingClientRect(),max=r.width*.32,dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,dist=Math.hypot(dx,dy),k=dist>max?max/dist:1;joy.x=dx*k/max;joy.y=dy*k/max;$('#knob').style.transform=`translate(${dx*k}px,${dy*k}px)`;}
stick.addEventListener('pointerdown',e=>{e.preventDefault();joyId=e.pointerId;stick.setPointerCapture(e.pointerId);stopMotion();updateJoy(e);});stick.addEventListener('pointermove',e=>{if(e.pointerId===joyId)updateJoy(e);});function endJoy(e){if(e.pointerId===joyId){joyId=null;joy.x=joy.y=0;$('#knob').style.transform='translate(0px,0px)';}}for(const t of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(t,endJoy);
for(const [id,value]of[['rise',1],['lower',-1]]){const b=$('#'+id);b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);stopMotion();rise=value;});for(const t of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(t,()=>rise=0);}
const handled=['KeyW','KeyA','KeyS','KeyD','KeyR','KeyF','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'];
window.addEventListener('keydown',e=>{if(e.key==='Escape'){resetInput();stopMotion();setGuide(false);toggleExplorer(false);closeDialogs();return;}if(document.querySelector('dialog[open]')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(handled.includes(e.code)){e.preventDefault();stopMotion();keys.add(e.code);}});window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{resetInput();pointers.clear();});document.addEventListener('visibilitychange',()=>{resetInput();last=performance.now();});
function resize(){if(!renderer||!camera)return;const w=world.clientWidth,h=world.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();mapDirty=true;updateLabels();}
window.addEventListener('resize',resize);small.addEventListener('change',()=>{setGuide(!small.matches);toggleExplorer(false);});
function tick(now){const dt=Math.min((now-last)/1000,.05);last=now;requestAnimationFrame(tick);if(!renderer||!camera||!scene||document.hidden){if(mapDirty)drawMap();return;}
 if(flight){const t=Math.min((now-flight.start)/flight.duration,1),ease=t*t*(3-2*t);camera.position.lerpVectors(flight.from,flight.to,ease);camera.position.y+=Math.sin(Math.PI*ease)*flight.arc;camera.quaternion.slerpQuaternions(flight.qFrom,flight.qTo,ease);if(t>=1){flight=null;$('#mode-label').textContent='自由探索';}}
 else if(mode==='orbit'&&landscape){orbitPhase+=dt*.1;const g=landscape.groups.get(selected);camera.position.set(g.position.x+Math.sin(orbitPhase)*orbitRadius,orbitHeight,g.position.z+Math.cos(orbitPhase)*orbitRadius);camera.lookAt(g.position.x,g.position.y+.7,g.position.z);}
 else {const forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-joy.y,right=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+joy.x,norm=Math.max(1,Math.hypot(forward,right)),yaw=camera.rotation.y;
 camera.position.x+=(-Math.sin(yaw)*forward+Math.cos(yaw)*right)/norm*speed*dt;camera.position.z+=(-Math.cos(yaw)*forward-Math.sin(yaw)*right)/norm*speed*dt;camera.position.y+=(rise+(keys.has('KeyR')?1:0)-(keys.has('KeyF')?1:0))*Math.max(speed*.8,.55)*dt;camera.rotation.y+=((keys.has('ArrowLeft')?1:0)-(keys.has('ArrowRight')?1:0))*dt*.75;camera.rotation.x+=((keys.has('ArrowUp')?1:0)-(keys.has('ArrowDown')?1:0))*dt*.65;}
 constrain();scene.fog.near=Math.max(110,camera.position.y*1.7);scene.fog.far=Math.max(440,camera.position.y*4+400);renderer.render(scene,camera);
 if(now-lastUi>110){updateLabels();const deg=((THREE.MathUtils.radToDeg(-camera.rotation.y)%360)+360)%360,dirs=['N','NE','E','SE','S','SW','W','NW'];$('#heading').textContent=dirs[Math.round(deg/45)%8];$('#compass-needle').style.transform=`rotate(${-deg}deg)`;$('#altitude').textContent=`視角約 ${Math.round(camera.position.y*100).toLocaleString()} m`;const[lon,lat]=unproject(camera.position.x,camera.position.z);$('#region-label').textContent=camera.position.y>150?'杭州—桐鄉 · 全域概覽':lat>.70?'桐鄉 · 烏鎮一帶':lat>.4?'江南平原 · 往烏鎮方向':lon>120.34?'杭州東部 · 蕭山一帶':lat<.19?'杭州 · 之江／濱江一帶':lon<120.10?'杭州 · 城西山水':lon<120.166&&lat<.275?'杭州 · 西湖一帶':'杭州 · 城區與錢塘江';drawMap();lastUi=now;}
}
requestAnimationFrame(tick);
